# site setting variables
# all of these can be accessed by {{ site.variable }}
title: etrog emoji
email:
description: >
  a real jackdaw.
baseurl: "" # defines subpath ie /path/, does not include hostname
url: "https://abysmalplain.github.io"
twitter_username:
github_username:

# build settings. i borrowed these from https://www.taniarascia.com/make-a-static-website-with-jekyll/
sass:
  sass_dir: _sass # declares _sass as the sass directory
include: ['_pages'] # forces custom pages to be organized into their own directory
kramdown:
  input: GFM
